### PR TITLE
Minerva nex deploy

### PR DESCRIPTION
**Pull request by kotfic**
Implements ansible deployment scripts to get NEX combination of plugins installed (girder, minerva, cumulus,  cumulus_frontend) - also ensures there is a running celery worker for cumulus and all girder dependencies are installed and running (e.g. mongodb)

To test checkout fresh copy and `vagrant up`

minerva should be on http://127.0.0.1:8080

you can log in with "admin/letmein"

@aashish24 PTAL

### CODE REVIEW

**Comment by kotfic** [comment]
@aashish24  This is still waiting on review.  thanks!

**Comment by aashish24** [comment]
Thanks for the reminder, I didn't realize that this was out. I will post my review today.

**Comment by kotfic** [comment]
@aashish24 if the plan is to still move forward with minerva/cumulus as-is then yes.

**Comment by aashish24** [comment]
Okay running now.

**Comment by aashish24** [comment]
@kotfic here is what i am getting now: 

fatal: [minerva]: FAILED! => {"changed": false, "failed": true, "msg": "<type 'exceptions.TypeError'>: user() takes at least 3 arguments (2 given)\n\nTraceback (most recent call last):\n  File \"/tmp/ansible_r24EV3/ansible_module_girder.py\", line 1362, in main\n    gcm(module)\n  File \"/tmp/ansible_r24EV3/ansible_module_girder.py\", line 686, in **call**\n    self.__process(method)\n  File \"/tmp/ansible_r24EV3/ansible_module_girder.py\", line 714, in __process\n    ret = getattr(self, method)(_args, *_kwargs)\nTypeError: user() takes at least 3 arguments (2 given)\n"}

**Comment by kotfic** [comment]
@aashish24 can you pull and try again?  This is now working for me with vagrant 1.8.4 and ansible 2.1.1 - I just had to update the girder ansible module

**Comment by aashish24** [comment]
LGTM :+1: :+1: thanks!

**Pull request merged**
