### PR TITLE
AWS ETL of GDDP data

### PR DESCRIPTION
**Pull request by kotfic**

### CODE REVIEW

**Comment by kotfic** [comment]
@aashish24

**Comment by kotfic** [comment]
@aashish24 Local testing of ETL is working on my end,  if you could test that would be great:

``` bash
# Clone the repo
git clone git@github.com:OpenGeoscience/nex.git
cd nex
git checkout aws_etl

# Launch the VM (should take ~10 minutes)
vagrant up
vagrant ssh
cd /vagrant

# Run the ETL script (on the VM should take around ~20 minutes)
# This will run:
#
# etl.delay(
# 'http://nasanex.s3.amazonaws.com/NEX-GDDP/BCSD/rcp45/day/atmos/pr/r1i1p1/v1.0/pr_day_BCSD_rcp45_r1i1p1_ACCESS1-0_2006.nc',
# 'http://nasanex.s3.amazonaws.com/NEX-GDDP/BCSD/rcp45/day/atmos/tasmin/r1i1p1/v1.0/tasmin_day_BCSD_rcp45_r1i1p1_ACCESS1-0_2006.nc',
# 'http://nasanex.s3.amazonaws.com/NEX-GDDP/BCSD/rcp45/day/atmos/tasmax/r1i1p1/v1.0/tasmax_day_BCSD_rcp45_r1i1p1_ACCESS1-0_2006.nc',
#  'day_BCSD_rcp45_r1i1p1_ACCESS1-0_2006.parquet')
#
python gddp_etl/__init__.py


# To watch progress
tail -F /var/log/celery/worker.log


# Once complete - verify on HDFS
#
# Should see something like:
# Found 1 items
# -rw-r--r--   1 vagrant supergroup 5027953248 2016-03-10 14:00 /home/ubuntu/day_BCSD_rcp45_r1i1p1_ACCESS1-0_2006.parquet
/opt/hadoop/2.7.1/bin/hadoop fs -ls /home/ubuntu/


# Launch spark-shell
/opt/spark-1.6.0-bin-hadoop2.6/bin/spark-shell --master=spark://localhost:7077


# From in the spark-shell
val df = sqlContext.read.format("parquet").load("hdfs://localhost:9000/home/ubuntu/")
df.show()

```

**Note** the VM is configured to use 8Gb RAM and 4 CPUs - these can be changed in the `Vagrantfile` if needed (L57,58) -  but I can't guarantee that you won't get OOM issues if you make them any lower.

**Comment by kotfic** [comment]
@aashish24 I am currently working on uploading to S3 - at the moment I am looking for a secure way to provide AWS credentials to the hadoop process,  it appears the standard way of doing this (e.g. through environment variables) is not currently implemented (See: [HADOOP-12807](https://issues.apache.org/jira/browse/HADOOP-12807))

**Comment by aashish24** [comment]
@kotfic LGTM :+1: Can you remove the WIP

**Comment by aashish24** [comment]
@kotfic I had to update the submodule reference `git submodule sync`

**Comment by aashish24** [comment]
@kotfic I am running now.

**Comment by aashish24** [comment]
this should be `/opt/hadoop/2.7.1/bin/hadoop -fs ls /home/ubuntu/`

`/opt/hadoop/2.7.1/bin/hadoop fs -ls /home/ubuntu/`

**Comment by aashish24** [comment]
@kotfic minor thing:

log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's repl log4j profile: org/apache/spark/log4j-defaults-repl.properties
To adjust logging level use sc.setLogLevel("INFO")
Welcome to

**Comment by aashish24** [comment]
@kotfic everything worked. great job @kotfic 

scala> df.show()
+-------+-----+---------+---------+---+---------+---------+
|    lat|  lon|     time|    model| pr|   tasmin|   tasmax|
+-------+-----+---------+---------+---+---------+---------+
|-89.625|0.375|852033600|ACCESS1-0|0.0| 274.4814|277.45853|
|-89.625|0.625|852033600|ACCESS1-0|0.0| 274.4868|277.47318|
|-89.625|0.875|852033600|ACCESS1-0|0.0|274.50226|277.45074|
|-89.625|1.125|852033600|ACCESS1-0|0.0|274.50485|277.44104|
|-89.625|1.375|852033600|ACCESS1-0|0.0|274.49878|277.44202|
|-89.625|1.625|852033600|ACCESS1-0|0.0|274.49948|277.41565|
|-89.625|1.875|852033600|ACCESS1-0|0.0|274.49414|277.38205|
|-89.625|2.125|852033600|ACCESS1-0|0.0| 274.4895| 277.3755|
|-89.625|2.375|852033600|ACCESS1-0|0.0|274.44693| 277.4029|
|-89.625|2.625|852033600|ACCESS1-0|0.0|274.41602|277.42303|
|-89.625|2.875|852033600|ACCESS1-0|0.0|274.42282|277.43015|
|-89.625|3.125|852033600|ACCESS1-0|0.0|274.42334|277.44162|
|-89.625|3.375|852033600|ACCESS1-0|0.0|274.41925| 277.4532|
|-89.625|3.625|852033600|ACCESS1-0|0.0| 274.4457| 277.4393|
|-89.625|3.875|852033600|ACCESS1-0|0.0|274.48016|277.42258|
|-89.625|4.125|852033600|ACCESS1-0|0.0| 274.4657| 277.4395|
|-89.625|4.375|852033600|ACCESS1-0|0.0|274.41382| 277.4701|
|-89.625|4.625|852033600|ACCESS1-0|0.0| 274.3826| 277.4958|
|-89.625|4.875|852033600|ACCESS1-0|0.0|274.39142|277.50082|
|-89.625|5.125|852033600|ACCESS1-0|0.0|274.39706|277.50995|
+-------+-----+---------+---------+---+---------+---------+
only showing top 20 rows

**Comment by aashish24** [comment]
I am merging it now.

**Pull request merged**
